from app.questions import FIELD_ORDER
from app.triage import classify


def fields(**known) -> dict:
    f = {name: None for name in FIELD_ORDER}
    f.update(known)
    return f


GOOD_GATES = dict(
    breathing=True, respiratory_rate=18, radial_pulse_present=True, obeys_commands=True
)


def test_ambulatory_is_minor():
    result = classify(fields(can_walk=True, **GOOD_GATES, trapped=False))
    assert result["category"] == "minor"


def test_all_gates_good_not_ambulatory_is_delayed():
    result = classify(fields(can_walk=False, **GOOD_GATES, trapped=False))
    assert result["category"] == "delayed"


def test_fast_breathing_is_immediate():
    result = classify(
        fields(can_walk=False, **{**GOOD_GATES, "respiratory_rate": 34}, trapped=False)
    )
    assert result["category"] == "immediate"


def test_no_pulse_is_immediate():
    result = classify(
        fields(can_walk=False, **{**GOOD_GATES, "radial_pulse_present": False})
    )
    assert result["category"] == "immediate"


def test_unknown_gate_escalates_to_immediate():
    """Unknown never clears a gate — safety constraint, not a preference."""
    partial = fields(can_walk=False, breathing=True, trapped=False)
    result = classify(partial)
    assert result["category"] == "immediate"
    assert "respiratory_rate" in result["unknown_gates"]


def test_no_response_is_immediate():
    result = classify(fields(), status="no_response")
    assert result["category"] == "immediate"


def test_trapped_ranks_above_untrapped_same_category():
    trapped = classify(fields(can_walk=False, **GOOD_GATES, trapped=True))
    free = classify(fields(can_walk=False, **GOOD_GATES, trapped=False))
    assert trapped["category"] == free["category"] == "delayed"
    assert trapped["score"] > free["score"]


def test_immediate_always_outranks_delayed_and_minor():
    immediate = classify(fields(can_walk=False, **{**GOOD_GATES, "breathing": False}))
    delayed = classify(fields(can_walk=False, **GOOD_GATES, trapped=True))
    minor = classify(fields(can_walk=True, trapped=True))
    assert immediate["score"] > delayed["score"] > minor["score"]


# --- reasoning trace: generated by the classifier as it evaluates ---


def test_trace_names_the_fired_rule():
    result = classify(
        fields(can_walk=False, **{**GOOD_GATES, "radial_pulse_present": False})
    )
    assert result["rule_fired"] == "gate_failed"
    fired = [e for e in result["trace"] if e["phase"] == "rule" and e["result"]]
    assert len(fired) == 1
    assert fired[0]["evaluated"] == {"failed_gates": ["radial_pulse_present"]}


def test_trace_stops_at_first_matching_rule():
    """Precedence is real: rules after the match are never evaluated,
    so they never appear in the trace."""
    result = classify(fields(can_walk=True, **GOOD_GATES, trapped=False))
    assert result["rule_fired"] == "ambulatory"
    rule_conditions = [e["condition"] for e in result["trace"] if e["phase"] == "rule"]
    assert rule_conditions == ['status == "no_response"', "can_walk == true"]


def test_trace_records_unknown_escalation():
    result = classify(fields(can_walk=False, breathing=True, trapped=False))
    assert result["rule_fired"] == "unknown_escalated"
    fired = next(e for e in result["trace"] if e["phase"] == "rule" and e["result"])
    assert "unknown" in fired["condition"]
    assert set(fired["evaluated"]["unknown_gates"]) == set(result["unknown_gates"])


def test_trace_gate_entries_record_values_read():
    result = classify(fields(can_walk=False, **{**GOOD_GATES, "breathing": False}))
    gates = [e for e in result["trace"] if e["phase"] == "gate"]
    assert len(gates) == 4
    breathing = next(e for e in gates if e["condition"] == "breathing == false")
    assert breathing["evaluated"] == {"breathing": False}
    assert breathing["result"] is True


def test_trace_score_entries_sum_to_score():
    for case in [
        fields(),
        fields(can_walk=True, **GOOD_GATES, trapped=False),
        fields(can_walk=False, **{**GOOD_GATES, "breathing": False}, trapped=True),
        fields(can_walk=False, breathing=True),
    ]:
        result = classify(case)
        points = sum(e.get("points", 0) for e in result["trace"] if e["phase"] == "score")
        assert points == result["score"]
